name: 'Quickstart Playwright End to End Tests'
description: 'Standardized Playwright end to end test for all FusionAuth Quickstart applications.'
inputs:
  FUSIONAUTH_URL:
    description: 'The FusionAuth URL.'
    required: false
    default: 'http://localhost:9011'
  QUICKSTART_URL:
    description: 'The URL of the Quickstart application.'
    required: false
    default: 'http://localhost:3000'
  ARTIFACT_PREFIX:
    description: 'The prefix for the generated playwright artifact. Especially useful for matrix workflows.'
    required: false
    default: 'playwright'
runs:
  using: "composite"
  steps:
    - name: Action Path
      run: echo $ACTION_PATH
      env:
        ACTION_PATH: ${{ github.action_path }}
      shell: bash

    - name: Action Repository
      run: echo $ACTION_REPOSITORY
      env:
        ACTION_PATH: ${{ github.action_repository }}
      shell: bash

    - name: Action Ref
      run: echo $ACTION_REF
      env:
        ACTION_PATH: ${{ github.action_ref }}
      shell: bash

    # Check FusionAuth status 5 times with increasing wait times.
    # Continue if FusionAuth status is OK or fail at the end.
    - name: Check FusionAuth status
      run: |
        for i in {1..5}; do
          if curl -s ${{ inputs.FUSIONAUTH_URL }}/api/status | grep -qi "ok"; then
            echo "FusionAuth is up and running."
            exit 0
          else
            echo "FusionAuth is not up and running. Waiting for $(expr 5 \* $i) seconds."
            sleep $(expr 5 \* $i)
          fi
        done
        exit 1
      shell: bash

    # Check Quickstart status 5 times with increasing wait times.
    # Continue if Quickstart is Reachable or fail at the end.
    - name: Check Quickstart status
      run: |
        for i in {1..5}; do
          if curl --write-out %{http_code} --silent --output /dev/null ${{ inputs.QUICKSTART_URL }} | grep -qi "200"; then
            echo "Quickstart is up and running."
            exit 0
          else
            echo "Quickstart is not up and running. Waiting for $(expr 5 \* $i) seconds."
            sleep $(expr 5 \* $i)
          fi
        done
        exit 1
      shell: bash

    - name: Setup Node
      uses: actions/setup-node@v5.0.0
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Run Playwright tests
      run: npx playwright test
      env:
        FUSIONAUTH_URL: ${{ inputs.FUSIONAUTH_URL }}/admin/
        QUICKSTART_URL: ${{ inputs.QUICKSTART_URL }}
      shell: bash
      working-directory: ${{ github.action_path }}

    - name: Upload Playwright results
      uses: actions/upload-artifact@v4.6.2
      if: ${{ !cancelled() }}
      with:
        name: ${{ inputs.ARTIFACT_PREFIX }}-report-${{github.run_number}}-${{github.run_attempt}}
        path: ${{ github.action_path }}/playwright-report/
        retention-days: 30
